package com.dqc.egsengine.feature.scaffold.domain

import com.dqc.egsengine.feature.scaffold.data.EgsConfigReader
import com.dqc.egsengine.feature.scaffold.data.FeatureDiUpdater
import com.dqc.egsengine.feature.scaffold.data.UseCaseScanner
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File

class PageScaffolderTemplateEngineTest {

    @Test
    fun `dry run uses project local android page template overrides`() {
        val projectRoot = createProjectFixture(projectType = "ANDROID", basePackage = "com.example")
        val override = projectRoot.resolve(".egs/templates/android/page/PageScreen.kt.ftl")
        override.parentFile.mkdirs()
        override.writeText(
            """
            package ${'$'}{screenDirPkg}

            fun ${'$'}{pascalName}Screen(): String = "project page override"
            """.trimIndent(),
        )

        val result = pageScaffolder().scaffold(
            projectRoot = projectRoot,
            moduleName = "task",
            pageName = "TaskDetail",
            useCases = emptyList(),
            dryRun = true,
        )

        val screen = result.files.single { it.path.endsWith("TaskDetailScreen.kt") }
        assertTrue(screen.content.contains("project page override"))
        assertTrue(screen.path.endsWith("presentation/screen/taskDetail/TaskDetailScreen.kt"))
        assertFalse(projectRoot.resolve("feature/task").exists())
    }

    @Test
    fun `dry run renders kmp page templates into commonMain layout`() {
        val projectRoot = createProjectFixture(projectType = "KMP", basePackage = "org.mifos")

        val result = pageScaffolder().scaffold(
            projectRoot = projectRoot,
            moduleName = "profile",
            pageName = "ProfileDetail",
            useCases = emptyList(),
            dryRun = true,
        )

        val screen = result.files.single { it.path.endsWith("ProfileDetailScreen.kt") }
        assertTrue(screen.content.contains("KMP screen scaffold generated by egs-engine"))
        assertTrue(
            screen.path.endsWith(
                "feature/profile/src/commonMain/kotlin/org/mifos/feature/profile/presentation/profileDetail/ProfileDetailScreen.kt",
            ),
        )
        assertTrue(result.files.none { it.path.contains("/src/main/kotlin/") })
    }

    private fun pageScaffolder(): PageScaffolder =
        PageScaffolder(
            configReader = EgsConfigReader(),
            useCaseScanner = UseCaseScanner(),
            diUpdater = FeatureDiUpdater(),
        )

    private fun createProjectFixture(projectType: String, basePackage: String): File {
        val root = kotlin.io.path.createTempDirectory("page-ftl-scaffold-test").toFile()
        root.resolve(".egs").mkdirs()
        root.resolve(".egs/config.json").writeText(
            """
            {
              "projectName": "fixture",
              "projectType": "$projectType",
              "rootPath": "${root.absolutePath.replace("\\", "\\\\")}",
              "conventionPluginId": "com.example.convention.feature",
              "basePackage": "$basePackage",
              "moduleStructure": {
                "layers": ["data", "domain", "presentation"],
                "hasRes": true
              },
              "baseClasses": [
                {
                  "name": "BaseViewModel",
                  "packageName": "$basePackage.feature.base.presentation.viewmodel",
                  "module": ":feature:base",
                  "filePath": "feature/base/BaseViewModel.kt",
                  "kind": "ABSTRACT_CLASS"
                }
              ]
            }
            """.trimIndent(),
        )
        root.resolve("settings.gradle.kts").writeText("""rootProject.name = "fixture"""")
        return root
    }
}
