package com.dqc.egsengine.feature.scaffold.presentation

import com.dqc.egsengine.feature.base.presentation.CliFormatter
import com.dqc.egsengine.feature.base.presentation.EgsCliCommand
import com.dqc.egsengine.feature.base.util.ProjectRootResolver
import com.dqc.egsengine.feature.scaffold.data.EgsConfigReader
import com.dqc.egsengine.feature.scaffold.data.ddl.SqlNaming
import com.dqc.egsengine.feature.scaffold.domain.effectiveBasePackage
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import org.koin.core.component.inject

/**
 * `egs client gen strings --module=X --keys=a,b,c` ¡ª writes a small `StringKeys` object for Compose/MR wiring.
 */
class ClientGenStringsCommand : EgsCliCommand(name = "strings") {
    private val configReader: EgsConfigReader by inject()

    private val moduleName by option("-m", "--module").required()

    private val keys by option(
        "--keys",
        help = "Comma-separated logical keys, e.g. loading,error_empty,retry",
    ).required()

    private val projectPath by option("--project", "-p").default(".")

    private val dryRun by option("--dry-run").flag()

    override fun runCommand() {
        val workspaceRoot = ProjectRootResolver.resolve(projectPath)
        val clientRoot = ProjectRootResolver.resolveGradleClientRoot(workspaceRoot)
        val config = configReader.readForScaffold(clientRoot, workspaceRoot)
        val base =
            config.effectiveBasePackage()
                ?: throw IllegalArgumentException("base package missing in .egs config")
        val modulePackage = "$base.feature.$moduleName"
        val pascal = SqlNaming.moduleNameToPascal(moduleName)
        val pkg = "$modulePackage.generated"
        val kotlinRoot =
            if (clientRoot.resolve("feature/$moduleName/src/commonMain/kotlin").isDirectory) {
                "src/commonMain/kotlin"
            } else {
                "src/main/kotlin"
            }
        val path = clientRoot.resolve("feature/$moduleName/$kotlinRoot/${pkg.replace('.', '/')}/StringKeys.kt")
        val keyList = keys.split(",").map { it.trim() }.filter { it.isNotEmpty() }
        val body =
            buildString {
                appendLine("/* Generated by egs client gen strings */")
                appendLine("package $pkg")
                appendLine()
                appendLine("object ${pascal}StringKeys {")
                keyList.forEach { k ->
                    val const = k.uppercase().replace(Regex("[^A-Z0-9]"), "_")
                    appendLine("    const val $const = \"$k\"")
                }
                appendLine("}")
            }
        if (dryRun) {
            echo(CliFormatter.formatInfo("Dry run: would write ${path.relativeTo(clientRoot).path}"))
            return
        }
        path.parentFile.mkdirs()
        path.writeText(body)
        echo(CliFormatter.formatSuccess("Wrote ${path.relativeTo(clientRoot).path}"))
    }
}
