/*
 * Copyright 2026 Mifos Initiative
 *
 * SPDX-License-Identifier: MPL-2.0
 */
package com.dqc.egsengine.feature.scaffold.domain

import com.dqc.egsengine.feature.init.data.GradleSourceRoots
import com.dqc.egsengine.feature.scaffold.data.EgsConfigReader
import com.dqc.egsengine.feature.scaffold.data.ddl.SqlNaming
import org.slf4j.LoggerFactory
import java.io.File

/**
 * Generates a [UseCase] skeleton and optional repository stubs / Koin registration.
 */
class CreateUseCaseScaffolder(
    private val configReader: EgsConfigReader,
) {
    private val logger = LoggerFactory.getLogger(CreateUseCaseScaffolder::class.java)

    data class ScaffoldResult(
        val files: List<File>,
        val dryRun: Boolean,
    )

    fun scaffold(
        clientRoot: File,
        workspaceRoot: File,
        moduleName: String,
        useCaseSimpleName: String,
        paged: Boolean,
        dryRun: Boolean,
    ): ScaffoldResult {
        val config = configReader.readForScaffold(clientRoot, workspaceRoot)
        val base = config.effectiveBasePackage()
            ?: throw IllegalArgumentException("Could not resolve base package from .egs config")
        val modulePackage = "$base.feature.$moduleName"
        val modulePascal = SqlNaming.moduleNameToPascal(moduleName)
        val pascalOp = useCaseSimpleName.replaceFirstChar { it.uppercase() }.removeSuffix("UseCase")
        val className = "${pascalOp}UseCase"
        val repositoryName = "${modulePascal}Repository"
        val kotlinRoot = kotlinRoot(clientRoot, moduleName)
        val pkgPath = modulePackage.replace(".", "/")
        val useCaseFile = clientRoot.resolve("feature/$moduleName/$kotlinRoot/$pkgPath/domain/usecase/$className.kt")

        val coreBase = "$base.core.base"
        val resultFqn = "$coreBase.network.domain.Result"
        val content = buildString {
            appendLine("/* Generated by egs create usecase - implement repository. */")
            appendLine("package $modulePackage.domain.usecase")
            appendLine()
            appendLine("import $modulePackage.domain.repository.$repositoryName")
            appendLine("import $resultFqn")
            appendLine()
            appendLine("internal class $className(")
            appendLine("    private val repository: $repositoryName,")
            appendLine(") {")
            if (paged) {
                appendLine("    suspend operator fun invoke(page: Int, pageSize: Int): $resultFqn<Any> {")
                appendLine("        TODO(\"Replace Any with PageResult<YourDto>; wire repository.fetch$pascalOp\")")
                appendLine("    }")
            } else {
                appendLine("    suspend operator fun invoke(): $resultFqn<Unit> =")
                appendLine("        repository.stub$pascalOp()")
            }
            appendLine("}")
        }

        val created = mutableListOf<File>()
        if (!dryRun) {
            useCaseFile.parentFile.mkdirs()
            useCaseFile.writeText(content)
            created.add(useCaseFile)
            appendRepositoryStubs(
                clientRoot,
                moduleName,
                modulePackage,
                kotlinRoot,
                modulePascal,
                pascalOp,
                paged,
                base,
            )
            appendDomainModule(clientRoot, moduleName, modulePackage, kotlinRoot, className, modulePackage)
        }
        logger.info("Use case scaffold: $className (dryRun=$dryRun)")
        return ScaffoldResult(files = created, dryRun = dryRun)
    }

    private fun kotlinRoot(clientRoot: File, moduleName: String): String {
        val mod = clientRoot.resolve("feature/$moduleName")
        val roots = GradleSourceRoots.orderedKotlinRoots(mod)
        val rel = roots.firstOrNull()?.relativeTo(mod)?.path ?: return "src/commonMain/kotlin"
        return if (rel.contains("commonMain")) "src/commonMain/kotlin" else "src/main/kotlin"
    }

    private fun appendRepositoryStubs(
        clientRoot: File,
        moduleName: String,
        modulePackage: String,
        kotlinRoot: String,
        modulePascal: String,
        opPascal: String,
        paged: Boolean,
        basePackage: String,
    ) {
        val pkgPath = modulePackage.replace(".", "/")
        val repoIf = clientRoot.resolve("feature/$moduleName/$kotlinRoot/$pkgPath/domain/repository/${modulePascal}Repository.kt")
        val repoImpl = clientRoot.resolve("feature/$moduleName/$kotlinRoot/$pkgPath/data/repository/${modulePascal}RepositoryImpl.kt")
        val coreBase = "$basePackage.core.base"
        val resultFqn = "$coreBase.network.domain.Result"
        if (repoIf.exists()) {
            var t = repoIf.readText()
            val sig =
                if (paged) {
                    "suspend fun fetch$opPascal(page: Int, pageSize: Int): $resultFqn<Any>"
                } else {
                    "suspend fun stub$opPascal(): $resultFqn<Unit>"
                }
            if (!t.contains("fun fetch$opPascal") && !t.contains("fun stub$opPascal")) {
                val insert = "\n    $sig\n"
                val idx = t.lastIndexOf('}')
                if (idx > 0) {
                    t = t.substring(0, idx) + insert + t.substring(idx)
                    repoIf.writeText(t)
                }
            }
        }
        if (repoImpl.exists()) {
            var t = repoImpl.readText()
            if (!t.contains("fetch$opPascal") && !t.contains("override fun stub$opPascal") && !t.contains("stub$opPascal")) {
                val block =
                    if (paged) {
                        """
                        override suspend fun fetch$opPascal(page: Int, pageSize: Int): $resultFqn<Any> {
                            TODO("Not yet implemented")
                        }
                        """.trimIndent()
                    } else {
                        """
                        override suspend fun stub$opPascal(): $resultFqn<Unit> {
                            TODO("Not yet implemented")
                        }
                        """.trimIndent()
                    }
                val idx = t.lastIndexOf('}')
                if (idx > 0) {
                    t = t.substring(0, idx) + "\n    $block\n" + t.substring(idx)
                    repoImpl.writeText(t)
                }
            }
        }
    }

    private fun appendDomainModule(
        clientRoot: File,
        moduleName: String,
        modulePackage: String,
        kotlinRoot: String,
        className: String,
        importPackage: String,
    ) {
        val pkgPath = modulePackage.replace(".", "/")
        val domainModule = clientRoot.resolve("feature/$moduleName/$kotlinRoot/$pkgPath/di/DomainModule.kt")
        if (!domainModule.exists()) return
        var t = domainModule.readText()
        if (t.contains("::$className")) return
        if (!t.contains("factoryOf")) {
            t = t.replace(
                "import org.koin.dsl.module",
                "import org.koin.dsl.module\nimport org.koin.core.module.dsl.factoryOf\nimport $importPackage.domain.usecase.$className",
            )
        } else if (!t.contains("import $importPackage.domain.usecase.$className")) {
            t = t.replace(
                "import org.koin.dsl.module",
                "import org.koin.dsl.module\nimport $importPackage.domain.usecase.$className",
            )
        }
        t = t.replace(
            "internal val domainModule = module {",
            "internal val domainModule = module {\n    factoryOf(::$className)",
        )
        domainModule.writeText(t)
    }
}
