/*
 * Feature module (KMP / Compose Multiplatform) — generated by egs-engine.
 */
plugins {
    alias(libs.plugins.cmp.feature.convention)
}

androidModule {
    namespace = "org.mifos.feature.profile"
}
