/*
 * Feature module (KMP / Compose Multiplatform) — generated by egs-engine.
 */
plugins {
    alias(libs.plugins.cmp.feature.ui.convention)
}

androidModule {
    namespace = "org.mifos.feature.profile"
}

kotlin {
    sourceSets {
        commonMain.dependencies {
            implementation(projects.coreBase.network)
        }
    }
}
