/*
 * KMP screen scaffold generated by egs-engine 1.0.
 */
package org.mifos.feature.task.presentation.taskList

import template.core.base.ui.UiEffect
import template.core.base.ui.UiIntent
import template.core.base.ui.UiState

internal interface TaskListContract {

    data class State(
        val isLoading: Boolean = false,
        val error: String? = null,
        val topicUpdateTopic: Boolean? = null,
    ) : UiState {
    }

    sealed class Intent : UiIntent {
        data class TopicUpdateTopic(
            val topicId: Long
        ) : Intent()
    }

    sealed class Effect : UiEffect {
        data class ShowToast(val message: String) : Effect()
    }
}
