/*
 * KMP screen scaffold generated by egs-engine 1.0.
 */
package org.mifos.feature.task.presentation.taskList

import template.core.base.ui.UiEffect
import template.core.base.ui.LoadableState
import template.core.base.ui.UiFailure
import template.core.base.ui.UiIntent

internal interface TaskListContract {

    data class State(
        override val isLoading: Boolean = false,
        override val failure: UiFailure? = null,
        val topicUpdateTopic: Boolean? = null,
    ) : LoadableState {
    }

    sealed class Intent : UiIntent {
        data class TopicUpdateTopic(
            val topicId: Long
        ) : Intent()
    }

    sealed class Effect : UiEffect {
        data class ShowToast(val message: String) : Effect()
    }
}
