/*
 * KMP screen scaffold generated by egs-engine.
 */
package org.mifos.feature.task.presentation.taskList

import template.core.base.ui.BaseViewModel
import org.mifos.feature.base.domain.result.Result
import org.mifos.feature.task.domain.usecase.TopicUpdateTopicUseCase

internal class TaskListViewModel(
    private val topicUpdateTopic: TopicUpdateTopicUseCase,
) : BaseViewModel<TaskListContract.State, TaskListContract.Intent, TaskListContract.Effect>(
    initialState = TaskListContract.State(),
) {

    override fun registerIntents() {
        registerIntent<TaskListContract.Intent.TopicUpdateTopic> {
            handleTopicUpdateTopic(it.topicId)
        }

    }

    private fun handleTopicUpdateTopic(topicId: Long) {
        launchRequest(showLoading = true) {
            when (val result = topicUpdateTopic(topicId = topicId)) {
                is Result.Success -> {
                    updateState { copy(topicUpdateTopic = result.value) }
                }
                is Result.Failure -> {
                    updateState { copy(error = result.throwable?.message) }
                }
            }
        }
    }

}
