/*
 * KMP screen scaffold generated by egs-engine.
 */
package org.mifos.feature.task.presentation.taskList

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.koin.compose.viewmodel.koinViewModel
import template.core.base.designsystem.theme.KptTheme
import template.core.base.ui.KptScaffold
import template.core.base.ui.KptScreenStateContent

@Composable
internal fun TaskListScreen(
    modifier: Modifier = Modifier,
) {
    val viewModel: TaskListViewModel = koinViewModel()
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    LaunchedEffect(Unit) {
        viewModel.effect.collect { effect ->
            when (effect) {
                is TaskListContract.Effect.ShowToast -> {
                    // Show toast or snackbar from the platform shell.
                }
            }
        }
    }


    KptScaffold(
        modifier = modifier.fillMaxSize(),
        title = "TaskList",
    ) {
        KptScreenStateContent(
            isLoading = uiState.isLoading,
            errorMessage = uiState.error,
            isEmpty = false,
            onRetry = { },
            modifier = Modifier.fillMaxSize(),
        ) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(KptTheme.spacing.md),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(
                    space = KptTheme.spacing.md,
                    alignment = Alignment.CenterVertically,
                ),
            ) {
                Text(
                    text = "TaskList",
                    color = KptTheme.colorScheme.onBackground,
                    style = KptTheme.typography.titleMedium,
                )
            }
        }
    }
}
