/*
 * KMP screen scaffold generated by egs-engine.
 */
package org.mifos.feature.task.presentation.taskList

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.koin.compose.viewmodel.koinViewModel

@Composable
internal fun TaskListScreen(
    modifier: Modifier = Modifier,
) {
    val viewModel: TaskListViewModel = koinViewModel()
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    LaunchedEffect(Unit) {
        viewModel.effect.collect { effect ->
            when (effect) {
                is TaskListContract.Effect.ShowToast -> {
                    // Show toast (Snackbar, platform dialog, etc.)
                }
            }
        }
    }


    Column(
        modifier = modifier.fillMaxSize().padding(16.dp),
    ) {
        when {
            uiState.isLoading -> {
                // LoadingIndicator
            }
            uiState.error != null -> {
                // Error UI; retry:
                // viewModel.sendIntent(TaskListContract.Intent.Retry)
            }
            else -> {
                // Content
            }
        }
    }
}
