/*
 * Feature module (KMP) — generated by egs-engine.
 */
package org.mifos.feature.profile.presentation.profile

import org.mifos.core.base.ui.UiEffect
import org.mifos.core.base.ui.UiIntent
import org.mifos.core.base.ui.UiState

internal interface ProfileContract {

    data class State(
        val isLoading: Boolean = false,
        val error: String? = null,
    ) : UiState

    sealed class Intent : UiIntent {
        data object Load : Intent()
    }

    sealed class Effect : UiEffect {
        data class ShowToast(val message: String) : Effect()
    }
}
