/*
 * Feature module (KMP) — generated by egs-engine.
 */
package org.mifos.feature.profile.presentation.profile

import org.mifos.core.base.ui.BaseViewModel

internal class ProfileViewModel(
    // Inject use cases when API sync adds them
) : BaseViewModel<ProfileContract.State, ProfileContract.Intent, ProfileContract.Effect>(
    initialState = ProfileContract.State(),
) {

    override fun registerIntents() {
        registerIntent<ProfileContract.Intent.Load> {
            // TODO: load data
        }
    }
}
