/*
 * Feature module (KMP) — generated by egs-engine.
 */
package org.mifos.feature.profile.presentation.profile

import org.mifos.core.base.ui.UiEffect
import org.mifos.core.base.ui.LoadableState
import org.mifos.core.base.ui.UiFailure
import org.mifos.core.base.ui.UiIntent

internal interface ProfileContract {

    data class State(
        override val isLoading: Boolean = false,
        override val failure: UiFailure? = null,
    ) : LoadableState

    sealed class Intent : UiIntent {
        data object Load : Intent()
    }

    sealed class Effect : UiEffect {
        data class ShowToast(val message: String) : Effect()
    }
}
