/*
 * Feature module (KMP)  generated by egs-engine.
 */
package org.mifos.feature.profile.presentation.profile

import androidx.compose.material3.Text
import androidx.compose.runtime.Composable

@Composable
internal fun ProfileScreen() {
    Text("Profile")
}
