/*
 * Feature module (KMP / Compose Multiplatform) — generated by egs-engine.
 */
plugins {
    alias(libs.plugins.${conventionPluginAlias})
}

androidModule {
    namespace = "${namespace}"
}

kotlin {
    sourceSets {
        commonMain.dependencies {
            implementation(projects.coreBase.network)
        }
    }
}
