/*
 * Feature module (KMP) — generated by egs-engine.
 */
package ${packageName}.presentation.${camel}

import template.core.base.ui.UiEffect
import template.core.base.ui.UiIntent
import template.core.base.ui.UiState

internal interface ${pascal}Contract {

    data class State(
        val isLoading: Boolean = false,
        val error: String? = null,
    ) : UiState

    sealed class Intent : UiIntent {
        data object Load : Intent()
    }

    sealed class Effect : UiEffect {
        data class ShowToast(val message: String) : Effect()
    }
}
