/*
 * Feature module (KMP) — generated by egs-engine.
 */
package ${packageName}.presentation.${camel}

import ${coreBase}.ui.UiEffect
import ${coreBase}.ui.UiIntent
import ${coreBase}.ui.UiState

internal interface ${pascal}Contract {

    data class State(
        val isLoading: Boolean = false,
        val error: String? = null,
    ) : UiState

    sealed class Intent : UiIntent {
        data object Load : Intent()
    }

    sealed class Effect : UiEffect {
        data class ShowToast(val message: String) : Effect()
    }
}
