/*
 * Feature module (KMP) — generated by egs-engine.
 */
package ${packageName}.presentation.${camel}

import ${coreBase}.ui.UiEffect
import ${coreBase}.ui.LoadableState
import ${coreBase}.ui.UiFailure
import ${coreBase}.ui.UiIntent

internal interface ${pascal}Contract {

    data class State(
        override val isLoading: Boolean = false,
        override val failure: UiFailure? = null,
    ) : LoadableState

    sealed class Intent : UiIntent {
        data object Load : Intent()
    }

    sealed class Effect : UiEffect {
        data class ShowToast(val message: String) : Effect()
    }
}
