/*
 * Feature module (KMP) — generated by egs-engine.
 */
package ${packageName}.di

import org.koin.core.module.dsl.bind
import org.koin.core.module.dsl.singleOf
import org.koin.dsl.module
import ${packageName}.data.repository.${pascal}RepositoryImpl
import ${packageName}.domain.repository.${pascal}Repository

internal val dataModule = module {
    singleOf(::${pascal}RepositoryImpl) { bind<${pascal}Repository>() }
}
