/*
 * Feature module (KMP) ¡ª generated by egs-engine.
 */
package ${packageName}.di

import org.koin.core.module.dsl.viewModelOf
import org.koin.dsl.module
import ${packageName}.presentation.${camel}.${pascal}ViewModel

internal val presentationModule = module {
    viewModelOf(::${pascal}ViewModel)
}
