/*
 * Feature module (KMP) ¡ª generated by egs-engine.
 * egs-codegen: scaffold-repository-impl  (after sync this extends generated API support; add // egs-sync:freeze to stop overwrites)
 */
package ${packageName}.data.repository

import ${packageName}.domain.repository.${pascal}Repository
import template.core.base.network.domain.Result

internal class ${pascal}RepositoryImpl : ${pascal}Repository {

    override suspend fun sample(): Result<String> = Result.Success(value = "ok")
}
