/*
 * Feature module (KMP) — generated by egs-engine.
 */
package ${packageName}.domain.repository

import template.core.base.network.domain.Result

/**
 * Domain repository contract. Regenerate or extend when running API sync.
 */
internal interface ${pascal}Repository {
    suspend fun sample(): Result<String>
}
