/*
 * Feature module (KMP) ¡ª generated by egs-engine.
 */
package ${packageName}.data.repository

import ${packageName}.domain.repository.${pascal}Repository
import template.core.base.network.domain.Result

internal class ${pascal}RepositoryImpl : ${pascal}Repository {

    override suspend fun sample(): Result<String> = Result.Success(value = "ok")
}
