/*
 * Feature module (KMP) ¡ª generated by egs-engine.
 */
package ${packageName}.di

import org.koin.core.module.Module
import org.koin.dsl.module

val feature${pascal}Modules: List<Module> = listOf(
    dataModule,
    domainModule,
    presentationModule,
)

val ${pascal}Module: Module = module {
    includes(feature${pascal}Modules)
}
