/*
 * Feature module (KMP) ¡ª generated by egs-engine.
 */
package ${packageName}

import org.koin.core.module.Module
import org.koin.dsl.module
import ${packageName}.data.dataModule
import ${packageName}.domain.domainModule
import ${packageName}.presentation.presentationModule

val feature${pascal}Modules: List<Module> = listOf(
    dataModule,
    domainModule,
    presentationModule,
)

val ${pascal}Module: Module = module {
    includes(feature${pascal}Modules)
}
