/*
 * Feature module (KMP)  generated by egs-engine.
 */
package ${packageName}.presentation.${camel}

import androidx.compose.material3.Text
import androidx.compose.runtime.Composable

@Composable
internal fun ${pascal}Screen() {
    Text("${pascal}")
}
