/*
 * Feature module (KMP) — generated by egs-engine.
 */
package ${packageName}.presentation.${camel}

import ${coreBase}.ui.BaseViewModel

internal class ${pascal}ViewModel(
    // Inject use cases when API sync adds them
) : BaseViewModel<${pascal}Contract.State, ${pascal}Contract.Intent, ${pascal}Contract.Effect>(
    initialState = ${pascal}Contract.State(),
) {

    override fun registerIntents() {
        registerIntent<${pascal}Contract.Intent.Load> {
            // TODO: load data
        }
    }
}
