/*
 * Feature module (KMP) — generated by egs-engine.
 */
package org.mifos.feature.profile.di

import org.koin.core.module.dsl.bind
import org.koin.core.module.dsl.singleOf
import org.koin.dsl.module
import org.mifos.feature.profile.data.repository.ProfileRepositoryImpl
import org.mifos.feature.profile.domain.repository.ProfileRepository

internal val dataModule = module {
    singleOf(::ProfileRepositoryImpl) { bind<ProfileRepository>() }
}
