/*
 * Feature module (KMP) — generated by egs-engine.
 */
package org.mifos.feature.profile.di

import org.koin.core.module.dsl.viewModelOf
import org.koin.dsl.module
import org.mifos.feature.profile.presentation.profile.ProfileViewModel

internal val presentationModule = module {
    viewModelOf(::ProfileViewModel)
}
