/*
 * Feature module (KMP) generated by egs-engine.
 */
package org.mifos.feature.profile.di

import org.koin.core.module.Module
import org.koin.dsl.module

val featureProfileModules: List<Module> = listOf(
    dataModule,
    domainModule,
    presentationModule,
)

val ProfileModule: Module = module {
    includes(featureProfileModules)
}
