extends "res://entities/skills/core/skill.gd"
class_name DoubleJump
## DoubleJump — generated by `egs game add skill double_jump`.
##
## Extends the Skill base Resource. Default field values live on the .tres
## instance (see double_jump.tres); override activate() for behaviour.

func activate(_context: Dictionary) -> void:
    super.activate(_context)
