/*
 * Feature module (KMP) generated by egs-engine.
 * egs-codegen: scaffold-repository-impl (after sync this extends generated API support; add // egs-sync:freeze to stop overwrites)
 */
package org.mifos.feature.profile.data.repository

import org.mifos.feature.profile.domain.repository.ProfileRepository
import org.mifos.core.base.network.domain.Result

internal class ProfileRepositoryImpl : ProfileRepository {

    override suspend fun sample(): Result<String> = Result.Success(value = "ok")
}
