extends "${baseScriptResPath}"
class_name ${className}
## ${className} — generated by `egs game add enemy ${name}`.
##
## Extends the Enemy base class, which already wires enemy/save groups,
## Hurtbox routing, and a StateMachine child. Override fields here and
## flesh out state scripts under a sibling StateMachine node.

func _ready() -> void:
    super._ready()
    display_name = "${displayLabel}"
    max_hp = 20.0
<#if templateId == "metroidvania">
    contact_damage = 8.0
    knockback_resist = 0.0
    drop_table = {}
</#if>
