extends "${baseScriptResPath}"
class_name ${className}
## ${className} — generated by `egs game add room ${name}`.
##
## Extends the Room base class, which emits room_entered and supports exit
## transitions via RoomManager. Set exits and connected_rooms here.

func _ready() -> void:
    super._ready()
    room_id = "${snakeName}"
    display_name = "${displayLabel}"
    exits = {}
<#if templateId == "metroidvania">
    explored = false
    minimap_icon = ""
    connected_rooms = []
</#if>
