extends "${baseScriptResPath}"
class_name ${className}
## ${className} — generated by `egs game add skill ${name}`.
##
## Extends the Skill base Resource. Default field values live on the .tres
## instance (see ${snakeName}.tres); override activate() for behaviour.

func activate(_context: Dictionary) -> void:
    super.activate(_context)
