extends "res://entities/enemies/core/enemy.gd"
class_name Slime
## Slime — generated by `egs game add enemy slime`.
##
## Extends the Enemy base class, which already wires enemy/save groups,
## Hurtbox routing, and a StateMachine child. Override fields here and
## flesh out state scripts under a sibling StateMachine node.

func _ready() -> void:
    super._ready()
    display_name = "Slime"
    max_hp = 20.0
