extends "res://entities/enemies/core/enemy.gd"
class_name PatrolBot
## PatrolBot — generated by `egs game add enemy patrol_bot`.
##
## Extends the Enemy base class, which already wires enemy/save groups,
## Hurtbox routing, and a StateMachine child. Override fields here and
## flesh out state scripts under a sibling StateMachine node.

func _ready() -> void:
    super._ready()
    display_name = "Patrol Bot"
    max_hp = 20.0
    contact_damage = 8.0
    knockback_resist = 0.0
    drop_table = {}
