/*
 * KMP screen scaffold generated by egs-engine.
 */
package ${screenPkg}

<#assign coreBasePkg = coreBase!"template.core.base">
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
<#if hasPagedOffset>
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.rememberLazyListState
</#if>
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.koin.compose.viewmodel.koinViewModel
import ${coreBasePkg}.designsystem.theme.KptTheme
<#if hasPagedOffset>
import ${coreBasePkg}.ui.KptPagingErrorContent
import ${coreBasePkg}.ui.KptPagingLoadingMoreContent
import ${coreBasePkg}.ui.KptPagingStateContent
<#else>
import ${coreBasePkg}.ui.KptScreenStateContent
</#if>
import ${coreBasePkg}.ui.KptScaffold
<#if hasPagedOffset>
import ${coreBasePkg}.ui.rememberKptPullToRefreshState
</#if>

@Composable
internal fun ${pascalName}Screen(
    modifier: Modifier = Modifier,
) {
    val viewModel: ${pascalName}ViewModel = koinViewModel()
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
<#if hasPagedOffset>
    val listState = rememberLazyListState()
    LaunchedEffect(listState.firstVisibleItemIndex, listState.layoutInfo.totalItemsCount, uiState.endReached) {
        val lastVisible = listState.layoutInfo.visibleItemsInfo.lastOrNull()?.index ?: return@LaunchedEffect
        if (uiState.endReached || uiState.items.isEmpty() || uiState.isLoadingMore) return@LaunchedEffect
        if (lastVisible >= uiState.items.size - 1) {
            viewModel.dispatch(${pascalName}Contract.Intent.LoadMore)
        }
    }
</#if>

    LaunchedEffect(Unit) {
        viewModel.effect.collect { effect ->
            when (effect) {
                is ${pascalName}Contract.Effect.ShowToast -> {
                    // Show toast or snackbar from the platform shell.
                }
            }
        }
    }

<#if hasPagedOffset>
    LaunchedEffect(Unit) {
        viewModel.dispatch(${pascalName}Contract.Intent.Refresh)
    }
</#if>

    KptScaffold(
        modifier = modifier.fillMaxSize(),
        title = "${pascalName}",
<#if hasPagedOffset>
        pullToRefreshState = rememberKptPullToRefreshState(
            isEnabled = true,
            isRefreshing = uiState.isRefreshing,
            onRefresh = { viewModel.dispatch(${pascalName}Contract.Intent.Refresh) },
        ),
</#if>
    ) {
<#if hasPagedOffset>
        KptPagingStateContent(
            state = uiState,
            onRetry = { viewModel.dispatch(${pascalName}Contract.Intent.Retry) },
            modifier = Modifier.fillMaxSize(),
        ) {
<#else>
        KptScreenStateContent(
            state = uiState,
            isEmpty = false,
            onRetry = { },
            modifier = Modifier.fillMaxSize(),
        ) {
</#if>
<#if hasPagedOffset>
            LazyColumn(
                state = listState,
                verticalArrangement = Arrangement.spacedBy(KptTheme.spacing.sm),
                modifier = Modifier
                    .fillMaxSize()
                    .padding(KptTheme.spacing.md),
            ) {
                items(uiState.items.size) { index ->
                    val item = uiState.items[index]
                    Text(
                        text = item.toString(),
                        color = KptTheme.colorScheme.onBackground,
                        style = KptTheme.typography.bodyLarge,
                    )
                }

                if (uiState.isLoadingMore) {
                    item {
                        KptPagingLoadingMoreContent()
                    }
                }

                uiState.pagingError?.message
                    ?.takeIf { uiState.items.isNotEmpty() }
                    ?.let { message ->
                        item {
                            KptPagingErrorContent(
                                message = message,
                                onRetry = { viewModel.dispatch(${pascalName}Contract.Intent.Retry) },
                            )
                        }
                    }
            }
<#else>
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(KptTheme.spacing.md),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(
                    space = KptTheme.spacing.md,
                    alignment = Alignment.CenterVertically,
                ),
            ) {
                Text(
                    text = "${pascalName}",
                    color = KptTheme.colorScheme.onBackground,
                    style = KptTheme.typography.titleMedium,
                )
            }
</#if>
        }
    }
}
