/*
 * KMP screen scaffold generated by egs-engine.
 */
package ${screenPkg}

import template.core.base.ui.BaseViewModel
import ${resultPackage}.Result
<#list useCases as uc>
import ${uc.packageName}.${uc.name}
</#list>

internal class ${pascalName}ViewModel(
<#if hasUseCases>
<#list useCases as uc>
    private val ${uc.camelName}: ${uc.name},
</#list>
</#if>
) : BaseViewModel<${pascalName}Contract.State, ${pascalName}Contract.Intent, ${pascalName}Contract.Effect>(
    initialState = ${pascalName}Contract.State(),
) {

    override fun registerIntents() {
<#if hasUseCases>
<#list useCases as uc>
        registerIntent<${pascalName}Contract.Intent.${uc.intentName}> {
<#if uc.parameters?has_content>
            ${uc.handlerName}(<#list uc.parameters as p>it.${p.name}<#if p_has_next>, </#if></#list>)
<#else>
            ${uc.handlerName}()
</#if>
        }

</#list>
<#else>
        registerIntent<${pascalName}Contract.Intent.Load> {
            // TODO: load data
        }
</#if>
    }

<#list useCases as uc>
<#assign h = useCaseHandlers[uc_index] />
<#if h.resultBased>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launchRequest(showLoading = ${h.showLoading?c}) {
<#if uc.parameters?has_content>
            when (val result = ${h.useCaseCamel}(<#list uc.parameters as p>${p.name} = ${p.name}<#if p_has_next>, </#if></#list>)) {
<#else>
            when (val result = ${h.useCaseCamel}()) {
</#if>
                is Result.Success -> {
                    updateState { copy(${h.useCaseCamel} = result.value) }
                }
                is Result.Failure -> {
                    updateState { copy(error = result.throwable?.message) }
                }
            }
        }
    }

<#elseif h.flowBased>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launch {
            // TODO: collect Flow from ${uc.name}
        }
    }

<#else>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launchRequest {
            // TODO: wire ${uc.name}
        }
    }

</#if>
</#list>
}
