/*
 * KMP screen scaffold generated by egs-engine.
 */
package ${screenPkg}

import template.core.base.ui.BaseViewModel
<#if hasResultBasedHandler>
import ${resultClassFqn}
</#if>
<#list useCases as uc>
import ${uc.packageName}.${uc.name}
</#list>

internal class ${pascalName}ViewModel(
<#if hasUseCases>
<#list useCases as uc>
    private val ${uc.camelName}: ${uc.name},
</#list>
</#if>
) : BaseViewModel<${pascalName}Contract.State, ${pascalName}Contract.Intent, ${pascalName}Contract.Effect>(
    initialState = ${pascalName}Contract.State(),
) {

    override fun registerIntents() {
<#if hasUseCases || hasPagedOffset>
<#list intentInners as intent>
        registerIntent<${pascalName}Contract.Intent.${intent.simpleName}> {
<#if hasPagedOffset && (intent.simpleName == "Refresh" || intent.simpleName == "Retry")>
            runPagedLoad(refresh = true)
<#elseif hasPagedOffset && intent.simpleName == "LoadMore">
            runPagedLoad(refresh = false)
<#else>
<#list useCases as uc>
<#if uc.intentName == intent.simpleName>
<#if intent.emptyParams>
            ${uc.handlerName}()
<#else>
            ${uc.handlerName}(<#list intent.params as p>it.${p.name}<#if p_has_next>, </#if></#list>)
</#if>
</#if>
</#list>
</#if>
        }

</#list>
<#else>
        registerIntent<${pascalName}Contract.Intent.Load> {
            // No use cases: add intents or wire loading here
        }
</#if>
    }

<#if hasPagedOffset && primaryPagedUseCaseCamel?has_content>
    private fun runPagedLoad(refresh: Boolean) {
        val s = currentState
        if (!refresh && s.isLoadingMore) return
        if (!refresh && s.endReached) return
        val nextPage = if (refresh) 0 else s.page + 1
        launchRequest(showLoading = false) {
            if (refresh) {
                updateState { copy(isRefreshing = true, error = null) }
            } else {
                updateState { copy(isLoadingMore = true, error = null) }
            }
            when (val result = ${primaryPagedUseCaseCamel}(${primaryPagedArgList})) {
                is Result.Success -> {
                    val pageResult = result.value
                    val merged = if (refresh) {
                        pageResult.list
                    } else {
                        currentState.items + pageResult.list
                    }
                    val ended = pageResult.page + 1 >= pageResult.totalPages
                    updateState {
                        copy(
                            items = merged,
                            page = pageResult.page,
                            pageSize = pageResult.pageSize,
                            total = pageResult.total,
                            totalPages = pageResult.totalPages,
                            endReached = ended,
                            isRefreshing = false,
                            isLoadingMore = false,
                            error = null,
                        )
                    }
                }
                is Result.Failure -> {
                    updateState {
                        copy(
                            error = result.throwable?.message,
                            isRefreshing = false,
                            isLoadingMore = false,
                        )
                    }
                }
            }
        }
    }

</#if>
<#list useCases as uc>
<#assign h = useCaseHandlers[uc_index] />
<#if h.pagedBased>
<#-- paged: handled by runPagedLoad -->
<#elseif h.pagedFlowBased>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launch {
            ${h.useCaseCamel}(<#list uc.parameters as p>${p.name} = ${p.name}<#if p_has_next>, </#if></#list>).collect { pagingData ->
                // Use androidx.paging.compose.collectAsLazyPagingItems(pagingData) on Android, or map PagingData in platform code.
                updateState { copy(error = null) }
            }
        }
    }

<#elseif h.resultBased>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launchRequest(showLoading = ${h.showLoading?c}) {
<#if uc.parameters?has_content>
            when (val result = ${h.useCaseCamel}(<#list uc.parameters as p>${p.name} = ${p.name}<#if p_has_next>, </#if></#list>)) {
<#else>
            when (val result = ${h.useCaseCamel}()) {
</#if>
                is Result.Success -> {
                    updateState { copy(${h.useCaseCamel} = result.value) }
                }
                is Result.Failure -> {
                    updateState { copy(error = result.throwable?.message) }
                }
            }
        }
    }

<#elseif h.flowBased>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launch {
<#if uc.parameters?has_content>
            ${h.useCaseCamel}(<#list uc.parameters as p>${p.name} = ${p.name}<#if p_has_next>, </#if></#list>).collect { value ->
<#else>
            ${h.useCaseCamel}().collect { value ->
</#if>
                updateState { copy(${h.useCaseCamel} = value, error = null) }
            }
        }
    }

<#elseif h.unitEntityEchoToState>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launchRequest {
<#if uc.parameters?has_content>
            ${h.useCaseCamel}(<#list uc.parameters as p>${p.name} = ${p.name}<#if p_has_next>, </#if></#list>)
            updateState { copy(${h.unitEchoStatePropertyName} = ${h.unitEchoParamName}, error = null) }
<#else>
            ${h.useCaseCamel}()
</#if>
        }
    }

<#elseif h.directReturnToState>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launchRequest {
<#if uc.parameters?has_content>
            val ret = ${h.useCaseCamel}(<#list uc.parameters as p>${p.name} = ${p.name}<#if p_has_next>, </#if></#list>)
<#else>
            val ret = ${h.useCaseCamel}()
</#if>
            updateState { copy(${h.directStatePropertyName} = ret, error = null) }
        }
    }

<#else>
    private fun ${h.handlerName}(<#list uc.parameters as p>${p.name}: ${p.kotlinType}<#if p_has_next>, </#if></#list>) {
        launchRequest {
<#if uc.parameters?has_content>
            ${h.useCaseCamel}(<#list uc.parameters as p>${p.name} = ${p.name}<#if p_has_next>, </#if></#list>)
<#else>
            ${h.useCaseCamel}()
</#if>
            // TODO: map result to State (or add Result / Flow return type to UseCase)
        }
    }

</#if>
</#list>
}
