/*
 * KMP screen scaffold generated by egs-engine.
 */
package ${screenPkg}

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.koin.compose.viewmodel.koinViewModel

@Composable
internal fun ${pascalName}Screen(
    modifier: Modifier = Modifier,
) {
    val viewModel: ${pascalName}ViewModel = koinViewModel()
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    LaunchedEffect(Unit) {
        viewModel.effect.collect { effect ->
            when (effect) {
                is ${pascalName}Contract.Effect.ShowToast -> {
                    // TODO: Show toast (Snackbar, platform dialog, etc.)
                }
            }
        }
    }

    Column(
        modifier = modifier.fillMaxSize().padding(16.dp),
    ) {
        when {
            uiState.isLoading -> {
                // TODO: LoadingIndicator
            }
            uiState.error != null -> {
                // TODO: Error UI
            }
            else -> {
                // TODO: Content
            }
        }
    }
}
