/*
 * KMP screen scaffold generated by egs-engine 1.0.
 */
package ${screenPkg}

<#list contractImports as imp>
${imp}
</#list>
import template.core.base.ui.UiEffect
import template.core.base.ui.UiIntent
import template.core.base.ui.UiState

internal interface ${pascalName}Contract {

    data class State(
        val isLoading: Boolean = false,
        val error: String? = null,
<#list stateFields as f>
        val ${f.name}: ${f.typeContractRef}? = null,
</#list>
    ) : UiState

    sealed class Intent : UiIntent {
<#if hasUseCases>
<#list intentInners as intent>
<#if intent.emptyParams>
        data object ${intent.simpleName} : Intent()
<#else>
        data class ${intent.simpleName}(
<#list intent.params as p>
            val ${p.name}: ${p.kotlinType}<#if p_has_next>,</#if>
</#list>
        ) : Intent()
</#if>
</#list>
<#else>
        data object Load : Intent()
</#if>
    }

    sealed class Effect : UiEffect {
        data class ShowToast(val message: String) : Effect()
    }
}
