extends "res://entities/skills/core/skill.gd"
class_name Fireball
## Fireball — generated by `egs game add skill fireball`.
##
## Extends the Skill base Resource. Default field values live on the .tres
## instance (see fireball.tres); override activate() for behaviour.

func activate(_context: Dictionary) -> void:
    super.activate(_context)
