/*
 * Feature module (KMP) — generated by egs-engine.
 */
package org.mifos.feature.profile.domain.repository

import template.core.base.network.domain.Result

/**
 * Domain repository contract. Regenerate or extend when running API sync.
 */
internal interface ProfileRepository {
    suspend fun sample(): Result<String>
}
