extends "res://entities/rooms/core/room.gd"
class_name BossArena
## BossArena — generated by `egs game add room boss_arena`.
##
## Extends the Room base class, which emits room_entered and supports exit
## transitions via RoomManager. Set exits and connected_rooms here.

func _ready() -> void:
    super._ready()
    room_id = "boss_arena"
    display_name = "Boss Arena"
    exits = {}
